### ISSUE TITLE
Panic due to nil map assignment

### ISSUE THREAD

**Issue by negz** [crossplane-contrib/function-patch-and-transform#10]
@stevendborrelli observed this crash when running `function-patch-and-transform`.

```
kubectl logs -n crossplane-system function-patch-and-transform-2a8093bacea0-7cfdb7774b-lzwzz
{"level":"info","ts":1695993145.073164,"caller":"fn/fn.go:29","msg":"Running Function","tag":""}
panic: assignment to entry in nil map

goroutine 21 [running]:
main.(*Function).RunFunction(0x400051f430, {0x14f0ae0, 0x400015e030}, 0x40001080a0)
        /fn/fn.go:140 +0x1468
github.com/crossplane/function-sdk-go/proto/v1beta1._FunctionRunnerService_RunFunction_Handler({0x10c8120?, 0x400051f430}, {0x14f0ae0, 0x400015e030}, 0x4000350000, 0x0)
        /go/pkg/mod/github.com/crossplane/function-sdk-go@v0.0.0-20230927033848-4fd5cc3d7a44/proto/v1beta1/run_function_grpc.pb.go:104 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x40005661e0, {0x14f5f38, 0x4000503040}, 0x40003f0b40, 0x4000599170, 0x20213f0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.58.2/server.go:1376 +0xb90
google.golang.org/grpc.(*Server).handleStream(0x40005661e0, {0x14f5f38, 0x4000503040}, 0x40003f0b40, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.58.2/server.go:1753 +0x80c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /go/pkg/mod/google.golang.org/grpc@v1.58.2/server.go:998 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/pkg/mod/google.golang.org/grpc@v1.58.2/server.go:996 +0x164
```

It only seems to happen in a real Crossplane deployment, not using `xrender`. He mentioned he believes it was related to this resource:

```yaml
   - name: RDSInstanceSmall
          base:
            apiVersion: rds.aws.upbound.io/v1beta1
            kind: Instance
            spec:
              forProvider:
                region: us-west-2
                dbSubnetGroupNameSelector:
                  matchControllerRef: true
                instanceClass: db.t3.micro
                username: masteruser
                skipFinalSnapshot: true
                publiclyAccessible: false
                dbName: upbound # create custom database within the instance by default
              deletionPolicy: Delete
          patches:
            - fromFieldPath: "metadata.uid"
              toFieldPath: "spec.writeConnectionSecretToRef.name"
              transforms:
              - type: string
                string:
                  type: Format
                  fmt: "%s-sql" #change
```

**Comment by negz** [comment]
https://github.com/crossplane-contrib/function-patch-and-transform/blob/0ecfd98a24ead9b02288d43311f147fb06c6f5c6/fn.go#L140

I'm guessing this is the culprit.

**Comment by negz** [comment]
I can reproduce this at 3426939a67b77fb531fab972169cbaec40c99f78 using `xrender` with the following Composition:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xclusters.aws.caas.upbound.io
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: aws.caas.upbound.io/v1alpha1
    kind: XCluster
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: composite-network-eks
        base:
          apiVersion: aws.caas.upbound.io/v1alpha1
          kind: XNetwork
        connectionDetails:
        # This (or any connection detail we'll try to copy to the XR) is the culprit
        - name: boom
          type: FromValue
          value: kaboom!
```
