### ISSUE TITLE
Merge patch behavior not compatible with Native P&T

### ISSUE THREAD

**Issue by ravilr** [crossplane-contrib/function-patch-and-transform#101]
### What happened?

Seeing some compatibility issues in merge patch behavior between Native P&T and the [latest function-p-and-t:v0.4.0](https://github.com/crossplane-contrib/function-patch-and-transform/releases).  Looking for guidance on how to make the migration of compositions using native P&T to function-p-and-t _seamless_. 

See repro below. To summarize as per my understanding/observation from below resources:

1. function-p-and-t don't have an equivalent of `policy.mergeOptions.keepMapValues: false`. the function-p&t default `toFieldPath: Replace` will replace the dst with src.  the newly added `toFieldPath: MergeObject` which is equivalent to `keepMapValues: true` isn't what is needed here.  with `keepMapValues: false`, mergo's overwrite configuration gets enabled in native P&T https://github.com/darccio/mergo/blob/v1.0.0/merge.go#L322, which isn't possible in functions-p-and-t today..

2. the AppendArray merge option in functions-p-and-t isn't resulting in de-duplication of slice items, resulting in duplicate slice items after merge. whereas in Native P&T, `appendSlice: true` results in deduplication of slice items, so no duplicate in the destination after merge.. Any idea, why do we see this difference in behavior b/w function and native ?

### How can we reproduce it?

- Apply the below XRD spec and the Composition and Claim resources targeting Native P&T  and the same targeting function-p&t.

```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-nop
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-nop:v0.2.1
  ignoreCrossplaneConstraints: true
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  ignoreCrossplaneConstraints: false
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.4.0
  packagePullPolicy: IfNotPresent
  skipDependencyResolution: true
---
# XRD spec
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnopresources.nop.example.org
spec:
  group: nop.example.org
  names:
    kind: XNopResource
    plural: xnopresources
  claimNames:
    kind: NopResource
    plural: nopresources
  connectionSecretKeys:
  - test
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
     openAPIV3Schema:
       type: object
       properties:
        spec:
          type: object
          properties:
            coolField:
              type: string
            testConfig:
              type: object
              description: Test Map Configuration
              x-kubernetes-preserve-unknown-fields: true
          required:
          - coolField
---
# Native P&T Composition           
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnopresources-nativept.nop.example.org
  labels:
    xr-template-source: native-p-and-t
spec:
  compositeTypeRef:
    apiVersion: nop.example.org/v1alpha1
    kind: XNopResource
  resources:
  - name: nop-resource-1
    base:
     apiVersion: nop.crossplane.io/v1alpha1
     kind: NopResource
     spec:
      forProvider:
        conditionAfter:
        - conditionType: Ready
          conditionStatus: "False"
          time: 0s
        - conditionType: Ready
          conditionStatus: "True"
          time: 1s
        fields:
          environment: prod
          eks_version: "1.28"
          region: ""
      
          cilium:
            enabled: true
            mode: hybrid

          flux:
            enabled: true

          identity_provider:
            enabled: true
            groups:
              - 12345678

    patches:
      - fromFieldPath: spec.testConfig
        toFieldPath: spec.forProvider.fields
        policy:
          fromFieldPath: Required
          mergeOptions:
            keepMapValues: false
        type: FromCompositeFieldPath

      - fromFieldPath: spec.testConfig.identity_provider.groups
        toFieldPath: spec.forProvider.fields.identity_provider.groups
        type: FromCompositeFieldPath
        policy:
          mergeOptions:
            appendSlice: true
---
# A Claim targeting native P&T
apiVersion: nop.example.org/v1alpha1
kind: NopResource
metadata:
  namespace: default
  name: lifecycle-upgrade-1
spec:
  compositionSelector:
    matchLabels:
      xr-template-source: native-p-and-t
  coolField: "cool"
  compositeDeletePolicy: Foreground
  testConfig:
    environment: dev
    eks_version: "1.29"
    region: "use1"

    cilium:
      enabled: true
      mode: full

    identity_provider:
      enabled: true
      groups:
        - 12345678
---
# Same Composition converted to use functions P&T pipeline
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnopresources-xfn.nop.example.org
  labels:
    xr-template-source: function-p-and-t
spec:
  compositeTypeRef:
    apiVersion: nop.example.org/v1alpha1
    kind: XNopResource
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      environment: null
      kind: Resources
      patchSets: []
      resources:
      - base:
          apiVersion: nop.crossplane.io/v1alpha1
          kind: NopResource
          spec:
            forProvider:
              conditionAfter:
              - conditionStatus: "False"
                conditionType: Ready
                time: 0s
              - conditionStatus: "True"
                conditionType: Ready
                time: 1s
              fields:
                environment: prod
                eks_version: "1.28"
                region: ""
            
                cilium:
                  enabled: true
                  mode: hybrid

                flux:
                  enabled: true

                identity_provider:
                  enabled: true
                  groups:
                    - 12345678              

        name: nop-resource-1
        patches:
        - fromFieldPath: spec.testConfig
          policy:
            fromFieldPath: Required
          toFieldPath: spec.forProvider.fields
          type: FromCompositeFieldPath
        - fromFieldPath: spec.testConfig.identity_provider.groups
          policy:
            toFieldPath: AppendArray
          toFieldPath: spec.forProvider.fields.identity_provider.groups
          type: FromCompositeFieldPath
    step: patch-and-transform
---
# A claim targetting function P&T Composition
apiVersion: nop.example.org/v1alpha1
kind: NopResource
metadata:
  namespace: default
  name: lifecycle-upgrade-2
spec:
  compositionSelector:
    matchLabels:
      xr-template-source: function-p-and-t
  coolField: "cool"
  compositeDeletePolicy: Foreground
  testConfig:
    environment: dev
    eks_version: "1.29"
    region: "use1"

    cilium:
      enabled: true
      mode: full

    identity_provider:
      enabled: true
      groups:
        - 12345678
```

the rendered desired MR resource by function-P&T isn't the same as the one rendered by Native P&T.  the vimdiff in below image:
<img width="1855" alt="Screenshot 2024-03-26 at 4 29 12 PM" src="https://github.com/crossplane-contrib/function-patch-and-transform/assets/3928411/b468a1f0-acc9-46da-85a8-32ebee2e2d67">

- the default `Replace` toField merge in function-p&t isn't equivalent to Native P&T's  `keepMapValues: false`, the non-overlapping map attributes from destination are lost with `Replace`.
- AppendArray in function-p&t doesn't seem to de-duplicate slices on merge, like the Native P&T does.

### What environment did it happen in?
Crossplane version:  v1.15.1
function-patch-and-transform: v0.4.0
