### ISSUE TITLE
Unknown toFieldPathPolicy error when MergeObjects policy is used

### ISSUE THREAD

**Issue by driosalido** [crossplane-contrib/function-patch-and-transform#104]
Hi! I'm trying to use the new `MergeObjects` policy option and I get the following error. The same composition without the affected patch works well.

```bash
crossplane beta render xencryptionkey-function.yaml ../apis/encryptionkey/aws.yaml functions.yaml
crossplane: error: cannot render composite resource: pipeline step "patch-and-transform" returned a fatal result: invalid Function input: resources[0].patches[1].policy.toFieldPathPolicy: Invalid value: "MergeObjects": unknown toFieldPathPolicy
```

In this composition resource definition

```yaml
        resources:
          - base:
              apiVersion: kms.aws.upbound.io/v1beta1
              kind: Key
              spec:
                deletionPolicy: Orphan
                forProvider: {}
                providerConfigRef:
                  name: default
            name: key
            patches:
              - patchSetName: common-fields
                type: PatchSet
              - fromFieldPath: metadata.labels
                policy:
                  toFieldPath: MergeObjects
                toFieldPath: metadata.labels
                type: FromCompositeFieldPath
```

I'm pretty sure that I've followed the documentation but I don't know why my `policy.toFieldPath` attribute gets translated into  `toFieldPathPolicy` 

Any idea why? am I doing something wrong?
