### ISSUE TITLE
Composite showing ready status when one of the resources cannot render

### ISSUE THREAD

**Issue by stevendborrelli** [crossplane-contrib/function-patch-and-transform#12]
In porting over [platform-ref-aws](https://github.com/upbound/platform-ref-aws) to P&T, I noticed that the Helm releases were unhealthy, but the overall composite showed healthy:

```
kubectl get composite 
xeks.aws.platformref.upbound.io/borrelli-function-test-9pq6z-62qdh   True     True    xeks.aws.platformref.upbound.io   70m
```

This helm ProviderConfig and KubernetesClusterAuth not generating was due to a patch that needed a field `Type` added to it:

```
        transforms:
                - type: string
                  string:
                    type: Format # missing
                    fmt: "%s-ekscluster"
```

```
  Warning  ComposeResources         4m48s (x43 over 70m)  defined/compositeresourcedefinition.apiextensions.crossplane.io  Pipeline step "patch-and-transform": cannot render FromComposite patches for composed resource "kubernetesClusterAuth": cannot apply the "FromCompositeFieldPath" patch at index 1: transform at index 0 returned error: string transform could not resolve: type  is not supported for string transform type
```

I believe this composite should have shown that it could not render a resource:

```
Status:
  Conditions:
    Last Transition Time:  2023-09-30T07:11:06Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
    Last Transition Time:  2023-09-30T08:19:07Z
    Reason:                Available
    Status:                True
    Type:                  Ready
```
