### ISSUE TITLE
Support for `ToEnvironmentFieldPath` patch type in `spec.environment.patches`

### ISSUE THREAD

**Issue by truongnht** [crossplane-contrib/function-patch-and-transform#123]
In `function-patch-and-transform` 0.2.1 we do have support for `ToEnvironmentFieldPath`, so the following was supported in our composition

```yaml
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        environment:
          patches:
            - type: ToEnvironmentFieldPath
              fromFieldPath: spec.parameters.serviceAccount.namespace
              toFieldPath: data.serviceAccountNamespace
            - type: ToEnvironmentFieldPath
              fromFieldPath: spec.parameters.serviceAccount.name
              toFieldPath: data.serviceAccountName
  ```
 
 However in latest release the `ToEnvironmentFieldPath` patch type is no longer supported, rather `FromCompositeFieldPath`. Since our platform supports also customer compositions, it is not easy bringing breaking changes without verifying with all customers. Our ask is to bring back the support for `To|FromEnvironmentFieldPath` in `spec.environment.patches`
