### ISSUE TITLE
Confusing error message when string transform is missing type

### ISSUE THREAD

**Issue by negz** [crossplane-contrib/function-patch-and-transform#15]
I had a string transform like this:

```yaml
            transforms:
              - type: string
                string:
                  fmt: "%s-aws-auth"
```

In this Function (unlike native P&T) the `type` field is required, so it should be:

```yaml
            transforms:
              - type: string
                string:
                  type: Format
                  fmt: "%s-aws-auth"
```

When it's missing, I get this confusing error:

```
Warning  ComposeResources         3m12s (x29 over 18m)  defined/compositeresourcedefinition.apiextensions.crossplane.io  Pipeline step "patch-and-transform": cannot render FromComposite patches for composed resource "aws-auth": cannot apply the "FromCompositeFieldPath" patch at index 1: transform at index 0 returned error: string transform could not resolve: type  is not supported for string transform type
```
