### ISSUE TITLE
Support transforms in connection details

### ISSUE THREAD

**Issue by bak-fts** [crossplane-contrib/function-patch-and-transform#177]
I would like greater control in how connection details are written to kubernetes secrets. One way to achieve this could be by allowing patch & transform style transforms in the `connectionDetails` items, like so:

```yaml
kind: Composition
spec:
  writeConnectionSecretsToNamespace: other-namespace
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: key
        base:
          # Removed for brevity
          spec:
            forProvider:
            # Removed for brevity
            writeConnectionSecretToRef:
              namespace: docs
              name: key1
        connectionDetails:
          - name: my-username
            type: FromConnectionSecretKey
            transforms:
              - type: string
                string:
                  type: Format
                  format: 'username = "%s"'
            fromConnectionSecretKey: username
```

This would allow me to use the resulting connection secret in the `varFiles` property of Terraform provider Workspaces.
