### ISSUE TITLE
Unable to patch labels

### ISSUE THREAD

**Issue by etutuit** [crossplane-contrib/function-patch-and-transform#221]
`function-patch-and-transform` in version `v0.9.0` is unable to patch `metadata.labels`. 

```yaml
---  
  # Removed for brevity  
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: kafka-topic
        patches:
          - type: FromCompositeFieldPath
            fromFieldPath: spec.exampleValue
            toFieldPath: metadata.labels["patchedLabel"]
          - type: FromCompositeFieldPath
            fromFieldPath: spec.exampleValue
            toFieldPath: metadata.annotations["patchedAnnotation"]
```

Using patches from example above will properly create `patchedAnnotation` annotation and silently ignore creation of `patchedLabel` label. 

Is this expected behaviour or should be considered bug, or missing feature?
