### ISSUE TITLE
Function cannot patch a desired.composed resource

### ISSUE THREAD

**Issue by ezgidemirel** [crossplane-contrib/function-patch-and-transform#27]
I may misunderstood how the function pipeline should work, but I assumed the following composition would create an S3 bucket: 

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbuckets.aws.platformref.upbound.io
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: aws.platformref.upbound.io/v1alpha1
    kind: XBucket
  mode: Pipeline
  pipeline:
    - step: create-base
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: ezgi-cool-bucket
            base:
              apiVersion: s3.aws.upbound.io/v1beta1
              kind: Bucket
              metadata:
                name: ezgi-cool-bucket
              spec:
                forProvider:
                  tags:
                    Name: ezgi-cool-bucket
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: ezgi-cool-bucket
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: "location"
                toFieldPath: "spec.forProvider.region"
                transforms:
                  - type: map
                    map:
                      EU: "eu-north-1"
                      US: "us-east-2"
    - step: ready
      functionRef:
        name: function-auto-ready
```
The composition above has two pipeline steps where the first step puts an S3 bucket resource without a required field in the desired state and the second step patches that required field to the resource. 

When I create the claim, I get the following error: 

```
  Warning  ComposeResources  54s (x31265 over 115m)  defined/compositeresourcedefinition.apiextensions.crossplane.io  (combined from similar events): cannot compose resources: cannot apply composed resource "ezgi-cool-bucket": Bucket.s3.aws.upbound.io "ezgi-bucket-cqm9c-scgrn" is invalid: spec.forProvider.region: Required value
```
