### ISSUE TITLE
Unable to install this function 

### ISSUE THREAD

**Issue by jtucci** [crossplane-contrib/function-patch-and-transform#47]
I wanted to give this a try and am unable to install this function using the following manifest 
```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.crossplane.io/crossplane-contrib/function-patch-and-transform:v0.2.1
```

When I deploy this resources It shows the following failed conditions 
```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
status:
  conditions:
    - lastTransitionTime: '2023-11-05T17:56:48Z'
      message: >-
        cannot unpack package: failed to fetch package digest from remote:
        failed to fetch package descriptor with a GET request after a previous
        HEAD request failure: HEAD
        https://xpkg.crossplane.io/v2/crossplane-contrib/function-patch-and-transform/manifests/v0.2.1:
        unexpected status code 404 Not Found (HEAD responses have no body, use
        GET for details): GET
        https://xpkg.crossplane.io/v2/crossplane-contrib/function-patch-and-transform/manifests/v0.2.1:
        NAME_UNKNOWN: repository name not known to registry; map[]
      reason: UnpackingPackage
      status: 'False'
      type: Installed
spec:
  ignoreCrossplaneConstraints: false
  package: xpkg.crossplane.io/crossplane-contrib/function-patch-and-transform:v0.2.1
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: default
  skipDependencyResolution: false

```

I wasn't able to find any additional documentation on running this from the crossplane docs or release notes. Am I missing something here?

**Comment by negz** [comment]
Whoops, it should be xpkg.upbound.io, not crossplane.io. Sorry! I just updated the releases:

```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.2.1
```
