### ISSUE TITLE
Tags are not being merged as expected

### ISSUE THREAD

**Issue by jcooklin** [crossplane-contrib/function-patch-and-transform#50]
Given a CompositeResourceDefinition with the following property.

```yaml
tags:
  x-kubernetes-map-type: granular
  additionalProperties:
    type: string
  description: Key-value map of resource tags.
  type: object
````

And a xr with the following field.

```yaml
tags:
      my-label: test
```

And P&T func configured like the following

```yaml
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: my-resource
            base: <redact>
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.tags
                toFieldPath: spec.initProvider.tags
```

The tags are being overwritten where I am expecting/hoping they will be merged.  

Please advise.
