### ISSUE TITLE
Environment patches ordering is different from that of Crossplane v1.13

### ISSUE THREAD

**Issue by phisco** [crossplane-contrib/function-patch-and-transform#54]
Same as https://github.com/crossplane/crossplane/issues/5050.
<details>
  <summary>functions.yaml</summary>

  ```yaml
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.2.1
  ```

</details>

<details>
  <summary>composition.yaml</summary>

```yaml
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: test-composition
spec:
  compositeTypeRef:
    apiVersion: example.com/v1alpha1
    kind: XTest
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      environment:
        environmentConfigs:
        - ref:
            name: test
          type: Reference
      kind: Resources
      resources:
      - name: test
        base:
          apiVersion: apiextensions.crossplane.io/v1alpha1
          kind: EnvironmentConfig
          metadata:
            name: result
          data:
            value: null
        patches:
        - fromFieldPath: value
          toFieldPath: data.value
          type: FromEnvironmentFieldPath
        - fromFieldPath: spec.testValue
          toFieldPath: data.value
          type: FromCompositeFieldPath
```

</details>

<details>
  <summary>xr.yaml</summary>

```yaml
---
apiVersion: example.com/v1alpha1
kind: XTest
metadata:
  name: test
spec:
  testValue: "From Composite"
```

</details>

```
$ crossplane beta render xr.yaml composition.yaml functions.yaml --context-values=apiextensions.crossplane.io/environment='{"value": "From environment"}'
---
apiVersion: example.com/v1alpha1
kind: XTest
metadata:
  name: test
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: EnvironmentConfig
metadata:
  annotations:
    crossplane.io/composition-resource-name: test
  generateName: test-
  labels:
    crossplane.io/composite: test
  ownerReferences:
  - apiVersion: example.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XTest
    name: test
    uid: ""
data:
  value: From environment    # <= this should have been "From Compositite"
```
