### ISSUE TITLE
Cannot retrieve data from an environmentConfig

### ISSUE THREAD

**Issue by Smana** [crossplane-contrib/function-patch-and-transform#56]
Hey,

I'm openning this issue following a [conversation in slack](https://crossplane.slack.com/archives/CEG3T90A1/p1700816636408649): I converted an existing composition using crossplane-migrator but I'm not able to read the data from the environment config anymore.

My composition is [here](https://github.com/Smana/demo-secured-eks/blob/harbor_functions/infrastructure/base/crossplane/configuration/sql-instance-composition.yaml) and I followed @phisco and @haarchri advise and added `data.` to the fromEnvironmentFielPath block.

```yaml
              - fromFieldPath: data.privateSubnetIds
                toFieldPath: spec.forProvider.subnetIds
                type: FromEnvironmentFieldPath
```

But I still get this error
```console
kubectl get subnetgroup.rds.aws.upbound.io/xplane-harbor-vqqnq-rr8hc -o yaml | grep -A 30 ^status:
status:
  atProvider: {}
  conditions:
  - lastTransitionTime: "2023-11-24T15:11:44Z"
    reason: Creating
    status: "False"
    type: Ready
  - lastTransitionTime: "2023-11-24T15:11:44Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2023-11-24T15:31:11Z"
    message: "async create failed: failed to create the resource: [{0 creating RDS
      DB Subnet Group (xplane-harbor-vqqnq-rr8hc): InvalidSubnet: Subnet IDs are required.\n\tstatus
      code: 400, request id: 701186a6-b34a-450d-b3de-f782f4781c07  []}]"
    reason: AsyncCreateFailure
    status: "False"
    type: LastAsyncOperation
```

**Comment by phisco** [comment]
@Smana, from the composition you've shared it looks like you misplaced the `environment.environmentConfig`, it should still be in the composition at `spec.environment.environmentConfig`, not at `spec.pipeline[0].environment.environmentConfig`, so as follows:
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    provider: aws
  name: xsqlinstances.cloud.ogenki.io
spec:
  compositeTypeRef:
    apiVersion: cloud.ogenki.io/v1alpha1
    kind: XSQLInstance
  environment:
    environmentConfigs:
      - ref:
          name: eks-environment
         type: Reference
  mode: Pipeline
  writeConnectionSecretsToNamespace: crossplane-system
  pipeline:
    - functionRef:
        name: function-patch-and-transform
      step: patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
...
```

**Comment by Smana** [comment]
I confirmed that worked fine (You just have an indentation problem in your code above)
```yaml
spec:
  compositeTypeRef:
    apiVersion: cloud.ogenki.io/v1alpha1
    kind: XSQLInstance
  environment:
    environmentConfigs:
      - ref:
          name: eks-environment
        type: Reference
```

Thank you @phisco
