### ISSUE TITLE
All environment patch types failing validation

### ISSUE THREAD

**Issue by sidpalas** [crossplane-contrib/function-patch-and-transform#86]
I am attempting to convert some compositions from `Resource` mode to `Pipeline` mode, but all of my environment patches are failing validation.

I'm using `xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.2.1` and rendering locally with the crossplane cli `v1.14.5`.

Here is a sample spec containing an environment patch:

```
spec:
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        environment:
          patches:
            - type: FromCompositeFieldPath
              fromFieldPath: foo
              toFieldPath: bar
```

This function (https://github.com/crossplane-contrib/function-patch-and-transform/blob/21742ed0204e5827100111d71562e3c668eeba59/validate.go#L93) seems like it ought to return nil (no error) in this case, but no matter what patch type (or any string actually...) I specify I always get:

```
crossplane: error: cannot render composite resource: pipeline step "patch-and-transform" returned a fatal result: invalid Function input: environment.patches[0][type]: Invalid value: "<TYPE>": invalid environment patch type
```
