### ISSUE TITLE
keepMapValues policy option doesn't keep existing values.

### ISSUE THREAD

**Issue by driosalido** [crossplane-contrib/function-patch-and-transform#90]
Composition migrated through the `crossplane-migrator` . The original composition works.

```
...
        resources:
          - name: cluster-addons
            base:
              apiVersion: intenthq.com/v1alpha1
              kind: XClusterAddon
              spec:
                compositionSelector:
                  matchLabels:
                    xclusteraddons.intenthq.com/type: main
                deletionPolicy: Delete
                parameters:
                  main:
                    helm:
                      values:
                        crossplane:
                          enabled: true
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.clusterAddons.values
                toFieldPath: spec.parameters.main.helm.values
                policy:
                  mergeOptions:
                    keepMapValues: true
```

and resource with

```
spec:
  parameters:
    clusterAddons:
      values:
        crossplane:
          helm:
            chart:
              version: 1.14.5
```

it's rendered as

```
spec:
  parameters:
    main:
      helm:
        values:
          crossplane:
            helm:
              chart:
                version: 1.14.5
```

missing the default values created in the composition

**Comment by driosalido** [comment]
Using 

```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: crossplane-contrib-function-patch-and-transform
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.3.0
```
