### ISSUE TITLE
MergeObject does not honour the same behaviour as Native P&T

### ISSUE THREAD

**Issue by fernandezcuesta** [crossplane-contrib/function-patch-and-transform#99]
When using a patch such as:

```yaml
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.tags
          toFieldPath: spec.forProvider.tags
          policy:
            toFieldPath: MergeObject
```

on a resource that looks like:

```yaml
      - name: public-subnet
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: Subnet
          metadata:
            labels:
              type: subnet
            name: # patched
          spec:
            forProvider:
              availabilityZone: # patched
              cidrBlock: # patched
              mapPublicIpOnLaunch: false
              tags:
                kubernetes.io/role/elb: "1"
```

I expected this to merge the existing tag (`kubernetes.io/role/elb: "1"`) to be merged with the object on `spec.parameters.tags`. However, this is not being the case and that _static_ tag is simply lost.

This behaves differently when compared to Native P&T and:

```yaml
    policy:
      mergeOptions:
        keepMapValues: true
```
